name = "pickshootreturn-presence"
main = "index.js"
compatibility_date = "2024-09-23"

[[durable_objects.bindings]]
name = "PRESENCE"
class_name = "PresenceDO"

[[durable_objects.bindings]]
name = "CHAT"
class_name = "ChatDO"

[[migrations]]
tag = "v1"
new_classes = ["PresenceDO"]

[[migrations]]
tag = "v2"
new_classes = ["ChatDO"]
